[package]
name = "html-builder"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"
license = "Unlicense"

[[bench]]
name = 'sample_html'
harness = false

[dev-dependencies]
criterion = "0.3.4"
pretty_assertions = "0.7.1"
